quarkus:
  cache:
    enabled: true
    caffeine:
      platform-client:
        metrics-enabled: true
        initial-capacity: 10
        expire-after-access: 5s
  redis:
    hosts: redis://localhost:6379
    password: 123456
  http:
    cors: true
    auth:
      permission:
        bearer:
          paths: /*
          policy: authenticated
          auth-mechanism: bearer
      proactive: true
  rest-client:
    verify-host: false
  swagger-ui:
    enable: true
    always-include: true
    title: 'Game Provider'
    path: api
  smallrye-openapi:
    info-title: 'Game Provider API'
    store-schema-directory: target
  banner:
    path: ascii-art
  native:
    resources:
      includes: publicKey.pem

smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem

mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
        issuer: https://www.megafair.com
#  openapi:
#    extensions:
#      smallrye:
#        info:
#          title: 'Game Provider API'
#          version: 1.0
#          description: 'Som desc'

disable:
  authorization: true

gp:
  cache:
    tokenTtl: 100m
    sessionTokenTtl: 10000000h